### ISSUE TITLE
issue with the display of multiple line annotations

### ISSUE THREAD

**Issue by secevo** [omnivore-app/logseq-omnivore#81]
![image](https://user-images.githubusercontent.com/2227386/225848838-b02933e9-99da-4678-914c-4ff9c2f0f68e.png)
The quote block seems to be only applying to the first line, which appears quite strange.

**Comment by sywhb** [comment]
We are working on creating highlight quote in markdown format in Omnivore to retain some of the HTML format including multi-line paragraphs

**Comment by jacksonh** [comment]
I think this is resolved with the new markdown highlights now. You would have to create a new highlight though to see the changes, it wont effect old highlights.

**Comment by sywhb** [comment]
@jacksonh I think this probably will be partially solved because there will still be issues with blockquote of multiple paragraphs: https://www.markdownguide.org/basic-syntax/#blockquotes-with-multiple-paragraphs

I have an idea to solve this but not finished yet

**Comment by sywhb** [comment]
Hey @yifeitao, we have fixed this in the latest release v1.12.4

Kindly upgrade your plugin and let me know if the issue persists.

Thanks!
